version: "3.9"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/styrn/sh/plex/config:/config
      - /home/styrn/sh/plex/transcode:/transcode
      - /home/styrn/media:/data
    environment:
      - TZ="America/Chicago"
      - PLEX_CLAIM=${PLEX_CLAIM}
