version: "3.9"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    volumes:
      - /plex/config:/config
      - /plex/transcode:/transcode
      - /mnt/media:/data
    environment:
      - TZ="America/Chicago"
      - PLEX_CLAIM=${PLEX_CLAIM}