version: "3.9"
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    restart: unless-stopped
    volumes:
      - /home/styrn/sh/plex/config:/config
      - /home/styrn/sh/plex/transcode:/transcode
      - /home/styrn/media:/data
    environment:
      - TZ="America/Chicago"
      - PLEX_CLAIM=${PLEX_CLAIM}
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - /home/styrn/sh/mosquitto:/mosquitto
      - /home/styrn/sh/mosquitto/data:/mosquitto/data
      - /home/styrn/sh/mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001